---
- name: Create config and data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: vault
    group: vault
    mode: '0750'
  loop:
    - /etc/vault.d/policies

- name: Upload Vault policy template
  template:
    src: vault_policy_snapshot.hcl.j2
    dest: /etc/vault.d/policies/snapshot.hcl
    owner: vault
    group: vault
    mode: '0644'

- name: Check if snapshot policy exists and matches
  shell: vault policy read snapshot
  register: snapshot_policy
  failed_when: false
  changed_when: false

- name: Apply Vault policy for snapshot access if missing or different
  become: true
  command: >
    vault policy write snapshot /etc/vault.d/policies/snapshot.hcl
  when: snapshot_policy.rc != 0

- name: Get current policies for backup role
  shell: vault read -field=token_policies auth/approle/role/backup
  register: backup_role_policies
  failed_when: false
  changed_when: false

- name: Apply snapshot policy to approle if not present
  command: >
    vault write auth/approle/role/backup token_policies="snapshot"
  when: backup_role_policies.rc != 0 or
        'snapshot' not in backup_role_policies.stdout.split(',')

