---
- name: Ensure role_id is saved locally
  block:
    - name: Read current role_id from Vault
      shell: vault read -field=role_id -format=json auth/approle/role/backup/role-id
      register: role_id_result
      changed_when: false
      retries: 5
      delay: 2
      until: role_id_result.rc == 0

    - name: Save role_id to local file if missing or changed
      copy:
        content: "{{ role_id_result.stdout }}"
        dest: "{{ host_dir }}/{{ approle_id_file }}"
      when: not lookup('file', host_dir + '/' + approle_id_file, errors='ignore') is defined or
            lookup('file', host_dir + '/' + approle_id_file, errors='ignore') != role_id_result.stdout

    - name: Set fact for role_id
      set_fact:
        approle_id: "{{ role_id_result.stdout }}"
      no_log: true

- name: Generate new secret_id
  block:
    - name: Write new secret_id
      shell: vault write -f -field=secret_id auth/approle/role/backup/secret-id
      register: secret_id_result
      changed_when: true

    - name: Save secret_id locally
      copy:
        content: "{{ secret_id_result.stdout }}"
        dest: "{{ host_dir }}/{{ approle_secret_file }}"
      no_log: true

    - name: Set fact for secret_id
      set_fact:
        approle_secret: "{{ secret_id_result.stdout }}"
      no_log: true

