---
- name: Save approle id
  shell: vault read auth/approle/role/backup/role-id --format=json | jq .data.role_id > {{ backup_dir }}/{{ approle_id_file }}

- name: Fetch approle id
  fetch:
    src: "{{ backup_dir }}/{{ approle_id_file }}"
    dest: "/tmp/"
    flat: yes
    fail_on_missing: false

- name: Read approle id to variable
  set_fact:
    approle_id: "{{ lookup('file', '/tmp/{{ approle_id_file }}') }}"
  no_log: true

- name: Save approle secret
  shell: vault write -f auth/approle/role/backup/secret-id --format=json | jq .data.secret_id > {{ backup_dir }}/{{ approle_secret_file }}

- name: Fetch approle secret
  fetch:
    src: "{{ backup_dir }}/{{ approle_secret_file }}"
    dest: "/tmp/"
    flat: yes
    fail_on_missing: false

- name: Read approle secret to variable
  set_fact:
    approle_secret: "{{ lookup('file', '/tmp/{{ approle_secret_file }}') }}"
  no_log: true
