---
- name: Check if backup exists
  stat:
    path: "{{ backup_dir }}/latest/vault.backup"
  register: vault_backup
  when: not (init_result.stdout | bool)

- name: Restore Vault from backup if it exists
  shell: /usr/local/bin/restore_vault.sh
  when: 
    - not (init_result.stdout | bool)
    - vault_backup.stat.exists
  register: restore_result
  changed_when: "'restored' in restore_result.stdout"

