---
- name: Deploy systemd service unit for Vault
  copy:
    src: vault.service
    dest: /etc/systemd/system/vault.service
    mode: '0644'

- name: Reload systemd and enable/start Vault
  systemd:
    name: vault
    daemon_reload: yes
    enabled: yes
    state: started

