docker_required_packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

docker_arch_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf

apt_keyring_path: /etc/apt/keyrings

docker_key_file: docker.asc
docker_repo_base_url: https://download.docker.com/linux/debian

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_cache_valid_time: 3600
