- name: Ensure required packages exists
  apt:
    name: jq
    state: present

- name: Check if backup file exists
  stat:
    path: /mnt/backup-nfs/vault/latest/vault.backup
  register: vault_backup

- name: Restore Vault from backup if it exists
  shell: /usr/local/bin/restore_vault.sh
  when: vault_backup.stat.exists
  register: restore_result
  changed_when: "'restored' in restore_result.stdout"

- name: Initialize Vault if no backup exists
  shell: |
    export VAULT_ADDR=http://127.0.0.1:8200
    vault operator init -key-shares=5 -key-threshold=3 -format=json > /mnt/backup-nfs/vault/init.json
    jq -r '.unseal_keys_b64[]' /mnt/backup-nfs/vault/init.json > /mnt/backup-nfs/vault/unseal-keys.txt
    jq -r '.root_token' /mnt/backup-nfs/vault/init.json > /mnt/backup-nfs/vault/root-token.txt
    chmod 600 /mnt/backup-nfs/vault/unseal-keys.txt
    chmod 600 /mnt/backup-nfs/vault/root-token.txt
  args:
    executable: /bin/bash
  when: not vault_backup.stat.exists

- name: Unseal Vault using unseal keys
  shell: |
    head -n 3 /mnt/backup-nfs/vault/unseal-keys.txt | while read key; do
      vault operator unseal "$key"
    done
  environment:
    VAULT_ADDR: http://127.0.0.1:8200
  changed_when: false

