---
- name: Ensure required packages are installed
  apt:
    name:
      - gnupg
      - wget
      - lsb-release
    state: present

- name: Add HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: '0644'
  register: hashicorp_key
  notify: Update apt cache

- name: Get Distro codename
  command: lsb_release -cs
  register: distro_codename
  changed_when: false

- name: Add HashiCorp APT repository
  copy:
    dest: /etc/apt/sources.list.d/hashicorp.list
    content: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ distro_codename.stdout }} main"
    mode: '0644'

- name: Install Vault
  apt:
    name: vault
    state: present
    update_cache: yes

