---
- name: Ensure Gotify directory exists
  file:
    path: "{{ docker_compose_dir }}/gotify"
    state: directory
    recurse: yes

- name: Deploy Gotify docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/gotify/docker-compose.yml"
    mode: '0644'

- name: Start Gotify container
  ansible.builtin.command: docker compose -f {{ docker_compose_dir }}/gotify/docker-compose.yml up -d

