diun_image: crazymax/diun:4.29
diun_data_path: /opt/diun/data
diun_env:
  - "TZ=Europe/Stockholm"
  - "DIUN_WATCH_WORKERS=20"
  - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
  - "DIUN_WATCH_JITTER=30s"
  - "DIUN_PROVIDERS_DOCKER=true"

