---
- name: Create config and data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: vault
    group: vault
    mode: '0750'
  loop:
    - /etc/vault.d/policies

- name: Upload Vault policy template
  template:
    src: vault_policy_snapshot.hcl.j2
    dest: /etc/vault.d/policies/snapshot.hcl
    owner: vault
    group: vault
    mode: '0644'

- name: Apply Vault policy for snapshot access
  command: >
    vault policy write snapshot /etc/vault.d/policies/snapshot.hcl

- name: Applt Vault policy snapshot to approle
  command: >
    vault write auth/approle/role/backup \
      token_policies="snapshot"

