---
- name: Fetch root token file
  fetch:
    src: "{{ backup_dir }}/{{ root_token_file }}"
    dest: "/tmp/"
    flat: yes
    fail_on_missing: false

- name: Read Vault root token to variable
  set_fact:
    vault_root_token: "{{ lookup('file', '/tmp/{{ root_token_file }}') }}"
  no_log: true

- name: Fetch root token file
  file:
    path: "{{ backup_dir }}/{{ root_token_file }}"
    state: absent

- name: Fetch unseal keys file
  fetch:
    src: "{{ backup_dir }}/{{ unseal_keys_file }}"
    dest: "/tmp/"
    flat: yes
    fail_on_missing: false

- name: Remove unseal keys file
  file:
    path: "{{ backup_dir }}/{{ unseal_keys_file }}"
    state: absent

- name: Fetch init file
  file:
    path: "{{ backup_dir }}/{{ init_file }}"
    state: absent

