- hosts: local
  become: true

  pre_tasks:
    - name: Update apt cache (Debian)
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
      when: ansible_os_family == 'Debian'

    - name: Update dnf cache (RedHat)
      ansible.builtin.dnf:
        update_cache: yes
      when: ansible_os_family == 'RedHat'
